version: '3'
services:
  app:
    image: python:3.8
    env_file:
      - envfiles/local.env
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - '../:/src'
    working_dir: '/src'
  db:
    image: postgres:12.10
    container_name: postoffice_django_db
    environment:
      - POSTGRES_PASSWORD=postoffice_django
      - POSTGRES_USER=postoffice_django
      - POSTGRES_DB=postoffice_django
    ports:
      - "6542:5432"
